-- ================================================================
-- schema.sql
-- Auto-generated by generate_schema.py
-- Do not edit manually. Re-run generate_schema.py to update.
-- Run this file in the Supabase SQL editor to set up your database.
-- ================================================================

--------------------------------------------------------------
-- TABLE: gdp
--------------------------------------------------------------

CREATE TABLE IF NOT EXISTS gdp (
    sasdate DATE NOT NULL,
    "GDPC1_t" NUMERIC,
    PRIMARY KEY (sasdate)
);

ALTER TABLE gdp ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon can read gdp" ON gdp;
CREATE POLICY "anon can read gdp"
    ON gdp
    FOR SELECT
    TO anon
    USING (true);

--------------------------------------------------------------
-- TABLE: fred_md
--------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fred_md (
    sasdate DATE NOT NULL,
    "RPI_t_md" NUMERIC,
    "W875RX1_t_md" NUMERIC,
    "DPCERA3M086SBEA_t_md" NUMERIC,
    "CMRMTSPLx_t_md" NUMERIC,
    "RETAILx_t_md" NUMERIC,
    "INDPRO_t_md" NUMERIC,
    "IPFPNSS_t_md" NUMERIC,
    "IPFINAL_t_md" NUMERIC,
    "IPCONGD_t_md" NUMERIC,
    "IPDCONGD_t_md" NUMERIC,
    "IPNCONGD_t_md" NUMERIC,
    "IPBUSEQ_t_md" NUMERIC,
    "IPMAT_t_md" NUMERIC,
    "IPDMAT_t_md" NUMERIC,
    "IPNMAT_t_md" NUMERIC,
    "IPMANSICS_t_md" NUMERIC,
    "IPB51222S_t_md" NUMERIC,
    "IPFUELS_t_md" NUMERIC,
    "CUMFNS_t_md" NUMERIC,
    "HWI_t_md" NUMERIC,
    "HWIURATIO_t_md" NUMERIC,
    "CLF16OV_t_md" NUMERIC,
    "CE16OV_t_md" NUMERIC,
    "UNRATE_t_md" NUMERIC,
    "UEMPMEAN_t_md" NUMERIC,
    "UEMPLT5_t_md" NUMERIC,
    "UEMP5TO14_t_md" NUMERIC,
    "UEMP15OV_t_md" NUMERIC,
    "UEMP15T26_t_md" NUMERIC,
    "UEMP27OV_t_md" NUMERIC,
    "CLAIMSx_t_md" NUMERIC,
    "PAYEMS_t_md" NUMERIC,
    "USGOOD_t_md" NUMERIC,
    "CES1021000001_t_md" NUMERIC,
    "USCONS_t_md" NUMERIC,
    "MANEMP_t_md" NUMERIC,
    "DMANEMP_t_md" NUMERIC,
    "NDMANEMP_t_md" NUMERIC,
    "SRVPRD_t_md" NUMERIC,
    "USTPU_t_md" NUMERIC,
    "USWTRADE_t_md" NUMERIC,
    "USTRADE_t_md" NUMERIC,
    "USFIRE_t_md" NUMERIC,
    "USGOVT_t_md" NUMERIC,
    "CES0600000007_t_md" NUMERIC,
    "AWOTMAN_t_md" NUMERIC,
    "AWHMAN_t_md" NUMERIC,
    "HOUST_t_md" NUMERIC,
    "HOUSTNE_t_md" NUMERIC,
    "HOUSTMW_t_md" NUMERIC,
    "HOUSTS_t_md" NUMERIC,
    "HOUSTW_t_md" NUMERIC,
    "AMDMNOx_t_md" NUMERIC,
    "AMDMUOx_t_md" NUMERIC,
    "BUSINVx_t_md" NUMERIC,
    "ISRATIOx_t_md" NUMERIC,
    "M1SL_t_md" NUMERIC,
    "M2SL_t_md" NUMERIC,
    "M2REAL_t_md" NUMERIC,
    "BOGMBASE_t_md" NUMERIC,
    "TOTRESNS_t_md" NUMERIC,
    "NONBORRES_t_md" NUMERIC,
    "BUSLOANS_t_md" NUMERIC,
    "REALLN_t_md" NUMERIC,
    "NONREVSL_t_md" NUMERIC,
    "CONSPI_t_md" NUMERIC,
    "S&P 500_t_md" NUMERIC,
    "S&P div yield_t_md" NUMERIC,
    "S&P PE ratio_t_md" NUMERIC,
    "FEDFUNDS_t_md" NUMERIC,
    "CP3Mx_t_md" NUMERIC,
    "TB3MS_t_md" NUMERIC,
    "TB6MS_t_md" NUMERIC,
    "GS1_t_md" NUMERIC,
    "GS5_t_md" NUMERIC,
    "GS10_t_md" NUMERIC,
    "AAA_t_md" NUMERIC,
    "BAA_t_md" NUMERIC,
    "COMPAPFFx_t_md" NUMERIC,
    "TB3SMFFM_t_md" NUMERIC,
    "TB6SMFFM_t_md" NUMERIC,
    "T1YFFM_t_md" NUMERIC,
    "T5YFFM_t_md" NUMERIC,
    "T10YFFM_t_md" NUMERIC,
    "AAAFFM_t_md" NUMERIC,
    "BAAFFM_t_md" NUMERIC,
    "EXSZUSx_t_md" NUMERIC,
    "EXJPUSx_t_md" NUMERIC,
    "EXUSUKx_t_md" NUMERIC,
    "EXCAUSx_t_md" NUMERIC,
    "WPSFD49207_t_md" NUMERIC,
    "WPSFD49502_t_md" NUMERIC,
    "WPSID61_t_md" NUMERIC,
    "WPSID62_t_md" NUMERIC,
    "PPICMM_t_md" NUMERIC,
    "CPIAUCSL_t_md" NUMERIC,
    "CPIAPPSL_t_md" NUMERIC,
    "CPITRNSL_t_md" NUMERIC,
    "CPIMEDSL_t_md" NUMERIC,
    "CUSR0000SAC_t_md" NUMERIC,
    "CUSR0000SAD_t_md" NUMERIC,
    "CUSR0000SAS_t_md" NUMERIC,
    "CPIULFSL_t_md" NUMERIC,
    "CUSR0000SA0L2_t_md" NUMERIC,
    "CUSR0000SA0L5_t_md" NUMERIC,
    "PCEPI_t_md" NUMERIC,
    "DDURRG3M086SBEA_t_md" NUMERIC,
    "DNDGRG3M086SBEA_t_md" NUMERIC,
    "DSERRG3M086SBEA_t_md" NUMERIC,
    "CES0600000008_t_md" NUMERIC,
    "CES2000000008_t_md" NUMERIC,
    "CES3000000008_t_md" NUMERIC,
    "DTCOLNVHFNM_t_md" NUMERIC,
    "DTCTHFNM_t_md" NUMERIC,
    "INVEST_t_md" NUMERIC,
    PRIMARY KEY (sasdate)
);

ALTER TABLE fred_md ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon can read fred_md" ON fred_md;
CREATE POLICY "anon can read fred_md"
    ON fred_md
    FOR SELECT
    TO anon
    USING (true);

--------------------------------------------------------------
-- TABLE: fred_qd_x
--------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fred_qd_x (
    sasdate DATE NOT NULL,
    "PCECC96_t_qd" NUMERIC,
    "PCDGx_t_qd" NUMERIC,
    "PCESVx_t_qd" NUMERIC,
    "PCNDx_t_qd" NUMERIC,
    "GPDIC1_t_qd" NUMERIC,
    "FPIx_t_qd" NUMERIC,
    "Y033RC1Q027SBEAx_t_qd" NUMERIC,
    "PNFIx_t_qd" NUMERIC,
    "PRFIx_t_qd" NUMERIC,
    "A014RE1Q156NBEA_t_qd" NUMERIC,
    "GCEC1_t_qd" NUMERIC,
    "A823RL1Q225SBEA_t_qd" NUMERIC,
    "FGRECPTx_t_qd" NUMERIC,
    "SLCEx_t_qd" NUMERIC,
    "EXPGSC1_t_qd" NUMERIC,
    "IMPGSC1_t_qd" NUMERIC,
    "DPIC96_t_qd" NUMERIC,
    "IPB51110SQ_t_qd" NUMERIC,
    "IPB51220SQ_t_qd" NUMERIC,
    "USPRIV_t_qd" NUMERIC,
    "USEHS_t_qd" NUMERIC,
    "USINFO_t_qd" NUMERIC,
    "USPBS_t_qd" NUMERIC,
    "USLAH_t_qd" NUMERIC,
    "USSERV_t_qd" NUMERIC,
    "USMINE_t_qd" NUMERIC,
    "CES9091000001_t_qd" NUMERIC,
    "CES9092000001_t_qd" NUMERIC,
    "CES9093000001_t_qd" NUMERIC,
    "CIVPART_t_qd" NUMERIC,
    "UNRATESTx_t_qd" NUMERIC,
    "UNRATELTx_t_qd" NUMERIC,
    "LNS14000012_t_qd" NUMERIC,
    "LNS14000025_t_qd" NUMERIC,
    "LNS14000026_t_qd" NUMERIC,
    "LNS12032194_t_qd" NUMERIC,
    "HOABS_t_qd" NUMERIC,
    "HOANBS_t_qd" NUMERIC,
    "HWIx_t_qd" NUMERIC,
    "HOUST5F_t_qd" NUMERIC,
    "RSAFSx_t_qd" NUMERIC,
    "PCECTPI_t_qd" NUMERIC,
    "PCEPILFE_t_qd" NUMERIC,
    "GDPCTPI_t_qd" NUMERIC,
    "GPDICTPI_t_qd" NUMERIC,
    "IPDBS_t_qd" NUMERIC,
    "DGDSRG3Q086SBEA_t_qd" NUMERIC,
    "DDURRG3Q086SBEA_t_qd" NUMERIC,
    "DSERRG3Q086SBEA_t_qd" NUMERIC,
    "DNDGRG3Q086SBEA_t_qd" NUMERIC,
    "DHCERG3Q086SBEA_t_qd" NUMERIC,
    "DMOTRG3Q086SBEA_t_qd" NUMERIC,
    "DFDHRG3Q086SBEA_t_qd" NUMERIC,
    "DREQRG3Q086SBEA_t_qd" NUMERIC,
    "DODGRG3Q086SBEA_t_qd" NUMERIC,
    "DFXARG3Q086SBEA_t_qd" NUMERIC,
    "DCLORG3Q086SBEA_t_qd" NUMERIC,
    "DGOERG3Q086SBEA_t_qd" NUMERIC,
    "DONGRG3Q086SBEA_t_qd" NUMERIC,
    "DHUTRG3Q086SBEA_t_qd" NUMERIC,
    "DHLCRG3Q086SBEA_t_qd" NUMERIC,
    "DTRSRG3Q086SBEA_t_qd" NUMERIC,
    "DRCARG3Q086SBEA_t_qd" NUMERIC,
    "DFSARG3Q086SBEA_t_qd" NUMERIC,
    "DIFSRG3Q086SBEA_t_qd" NUMERIC,
    "DOTSRG3Q086SBEA_t_qd" NUMERIC,
    "CPILFESL_t_qd" NUMERIC,
    "PPIACO_t_qd" NUMERIC,
    "WPSFD4111_t_qd" NUMERIC,
    "PPIIDC_t_qd" NUMERIC,
    "WPU0561_t_qd" NUMERIC,
    "CES2000000008x_t_qd" NUMERIC,
    "CES3000000008x_t_qd" NUMERIC,
    "COMPRNFB_t_qd" NUMERIC,
    "RCPHBS_t_qd" NUMERIC,
    "OPHNFB_t_qd" NUMERIC,
    "ULCBS_t_qd" NUMERIC,
    "ULCNFB_t_qd" NUMERIC,
    "UNLPNBS_t_qd" NUMERIC,
    "BAA10YM_t_qd" NUMERIC,
    "TB6M3Mx_t_qd" NUMERIC,
    "GS1TB3Mx_t_qd" NUMERIC,
    "GS10TB3Mx_t_qd" NUMERIC,
    "CPF3MTB3Mx_t_qd" NUMERIC,
    "BOGMBASEREALx_t_qd" NUMERIC,
    "M1REAL_t_qd" NUMERIC,
    "BUSLOANSx_t_qd" NUMERIC,
    "CONSUMERx_t_qd" NUMERIC,
    "NONREVSLx_t_qd" NUMERIC,
    "REALLNx_t_qd" NUMERIC,
    "TOTALSLx_t_qd" NUMERIC,
    "TABSHNOx_t_qd" NUMERIC,
    "TLBSHNOx_t_qd" NUMERIC,
    "LIABPIx_t_qd" NUMERIC,
    "TNWBSHNOx_t_qd" NUMERIC,
    "NWPIx_t_qd" NUMERIC,
    "TARESAx_t_qd" NUMERIC,
    "HNOREMQ027Sx_t_qd" NUMERIC,
    "TFAABSHNOx_t_qd" NUMERIC,
    "B020RE1Q156NBEA_t_qd" NUMERIC,
    "B021RE1Q156NBEA_t_qd" NUMERIC,
    "HWIURATIOx_t_qd" NUMERIC,
    "CONSPIx_t_qd" NUMERIC,
    "CP3M_t_qd" NUMERIC,
    "COMPAPFF_t_qd" NUMERIC,
    "NIKKEI225_t_qd" NUMERIC,
    "TLBSNNCBx_t_qd" NUMERIC,
    "TLBSNNCBBDIx_t_qd" NUMERIC,
    "TTAABSNNCBx_t_qd" NUMERIC,
    "TNWMVBSNNCBx_t_qd" NUMERIC,
    "TNWMVBSNNCBBDIx_t_qd" NUMERIC,
    "TLBSNNBx_t_qd" NUMERIC,
    "TLBSNNBBDIx_t_qd" NUMERIC,
    "TABSNNBx_t_qd" NUMERIC,
    "TNWBSNNBx_t_qd" NUMERIC,
    "TNWBSNNBBDIx_t_qd" NUMERIC,
    "CNCFx_t_qd" NUMERIC,
    "covid_crash_qd" NUMERIC,
    "covid_recover_qd" NUMERIC,
    PRIMARY KEY (sasdate)
);

ALTER TABLE fred_qd_x ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon can read fred_qd_x" ON fred_qd_x;
CREATE POLICY "anon can read fred_qd_x"
    ON fred_qd_x
    FOR SELECT
    TO anon
    USING (true);

--------------------------------------------------------------
-- TABLE: filled_md
--------------------------------------------------------------

CREATE TABLE IF NOT EXISTS filled_md (
    sasdate DATE NOT NULL,
    "RPI_t_md" NUMERIC,
    "W875RX1_t_md" NUMERIC,
    "DPCERA3M086SBEA_t_md" NUMERIC,
    "CMRMTSPLx_t_md" NUMERIC,
    "RETAILx_t_md" NUMERIC,
    "INDPRO_t_md" NUMERIC,
    "IPFPNSS_t_md" NUMERIC,
    "IPFINAL_t_md" NUMERIC,
    "IPCONGD_t_md" NUMERIC,
    "IPDCONGD_t_md" NUMERIC,
    "IPNCONGD_t_md" NUMERIC,
    "IPBUSEQ_t_md" NUMERIC,
    "IPMAT_t_md" NUMERIC,
    "IPDMAT_t_md" NUMERIC,
    "IPNMAT_t_md" NUMERIC,
    "IPMANSICS_t_md" NUMERIC,
    "IPB51222S_t_md" NUMERIC,
    "IPFUELS_t_md" NUMERIC,
    "CUMFNS_t_md" NUMERIC,
    "HWI_t_md" NUMERIC,
    "HWIURATIO_t_md" NUMERIC,
    "CLF16OV_t_md" NUMERIC,
    "CE16OV_t_md" NUMERIC,
    "UNRATE_t_md" NUMERIC,
    "UEMPMEAN_t_md" NUMERIC,
    "UEMPLT5_t_md" NUMERIC,
    "UEMP5TO14_t_md" NUMERIC,
    "UEMP15OV_t_md" NUMERIC,
    "UEMP15T26_t_md" NUMERIC,
    "UEMP27OV_t_md" NUMERIC,
    "CLAIMSx_t_md" NUMERIC,
    "PAYEMS_t_md" NUMERIC,
    "USGOOD_t_md" NUMERIC,
    "CES1021000001_t_md" NUMERIC,
    "USCONS_t_md" NUMERIC,
    "MANEMP_t_md" NUMERIC,
    "DMANEMP_t_md" NUMERIC,
    "NDMANEMP_t_md" NUMERIC,
    "SRVPRD_t_md" NUMERIC,
    "USTPU_t_md" NUMERIC,
    "USWTRADE_t_md" NUMERIC,
    "USTRADE_t_md" NUMERIC,
    "USFIRE_t_md" NUMERIC,
    "USGOVT_t_md" NUMERIC,
    "CES0600000007_t_md" NUMERIC,
    "AWOTMAN_t_md" NUMERIC,
    "AWHMAN_t_md" NUMERIC,
    "HOUST_t_md" NUMERIC,
    "HOUSTNE_t_md" NUMERIC,
    "HOUSTMW_t_md" NUMERIC,
    "HOUSTS_t_md" NUMERIC,
    "HOUSTW_t_md" NUMERIC,
    "AMDMNOx_t_md" NUMERIC,
    "AMDMUOx_t_md" NUMERIC,
    "BUSINVx_t_md" NUMERIC,
    "ISRATIOx_t_md" NUMERIC,
    "M1SL_t_md" NUMERIC,
    "M2SL_t_md" NUMERIC,
    "M2REAL_t_md" NUMERIC,
    "BOGMBASE_t_md" NUMERIC,
    "TOTRESNS_t_md" NUMERIC,
    "NONBORRES_t_md" NUMERIC,
    "BUSLOANS_t_md" NUMERIC,
    "REALLN_t_md" NUMERIC,
    "NONREVSL_t_md" NUMERIC,
    "CONSPI_t_md" NUMERIC,
    "S&P 500_t_md" NUMERIC,
    "S&P div yield_t_md" NUMERIC,
    "S&P PE ratio_t_md" NUMERIC,
    "FEDFUNDS_t_md" NUMERIC,
    "CP3Mx_t_md" NUMERIC,
    "TB3MS_t_md" NUMERIC,
    "TB6MS_t_md" NUMERIC,
    "GS1_t_md" NUMERIC,
    "GS5_t_md" NUMERIC,
    "GS10_t_md" NUMERIC,
    "AAA_t_md" NUMERIC,
    "BAA_t_md" NUMERIC,
    "COMPAPFFx_t_md" NUMERIC,
    "TB3SMFFM_t_md" NUMERIC,
    "TB6SMFFM_t_md" NUMERIC,
    "T1YFFM_t_md" NUMERIC,
    "T5YFFM_t_md" NUMERIC,
    "T10YFFM_t_md" NUMERIC,
    "AAAFFM_t_md" NUMERIC,
    "BAAFFM_t_md" NUMERIC,
    "EXSZUSx_t_md" NUMERIC,
    "EXJPUSx_t_md" NUMERIC,
    "EXUSUKx_t_md" NUMERIC,
    "EXCAUSx_t_md" NUMERIC,
    "WPSFD49207_t_md" NUMERIC,
    "WPSFD49502_t_md" NUMERIC,
    "WPSID61_t_md" NUMERIC,
    "WPSID62_t_md" NUMERIC,
    "PPICMM_t_md" NUMERIC,
    "CPIAUCSL_t_md" NUMERIC,
    "CPIAPPSL_t_md" NUMERIC,
    "CPITRNSL_t_md" NUMERIC,
    "CPIMEDSL_t_md" NUMERIC,
    "CUSR0000SAC_t_md" NUMERIC,
    "CUSR0000SAD_t_md" NUMERIC,
    "CUSR0000SAS_t_md" NUMERIC,
    "CPIULFSL_t_md" NUMERIC,
    "CUSR0000SA0L2_t_md" NUMERIC,
    "CUSR0000SA0L5_t_md" NUMERIC,
    "PCEPI_t_md" NUMERIC,
    "DDURRG3M086SBEA_t_md" NUMERIC,
    "DNDGRG3M086SBEA_t_md" NUMERIC,
    "DSERRG3M086SBEA_t_md" NUMERIC,
    "CES0600000008_t_md" NUMERIC,
    "CES2000000008_t_md" NUMERIC,
    "CES3000000008_t_md" NUMERIC,
    "DTCOLNVHFNM_t_md" NUMERIC,
    "DTCTHFNM_t_md" NUMERIC,
    "INVEST_t_md" NUMERIC,
    PRIMARY KEY (sasdate)
);

ALTER TABLE filled_md ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon can read filled_md" ON filled_md;
CREATE POLICY "anon can read filled_md"
    ON filled_md
    FOR SELECT
    TO anon
    USING (true);

--------------------------------------------------------------
-- TABLE: filled_qd
--------------------------------------------------------------

CREATE TABLE IF NOT EXISTS filled_qd (
    sasdate DATE NOT NULL,
    "PCECC96_t_qd" NUMERIC,
    "PCDGx_t_qd" NUMERIC,
    "PCESVx_t_qd" NUMERIC,
    "PCNDx_t_qd" NUMERIC,
    "GPDIC1_t_qd" NUMERIC,
    "FPIx_t_qd" NUMERIC,
    "Y033RC1Q027SBEAx_t_qd" NUMERIC,
    "PNFIx_t_qd" NUMERIC,
    "PRFIx_t_qd" NUMERIC,
    "A014RE1Q156NBEA_t_qd" NUMERIC,
    "GCEC1_t_qd" NUMERIC,
    "A823RL1Q225SBEA_t_qd" NUMERIC,
    "FGRECPTx_t_qd" NUMERIC,
    "SLCEx_t_qd" NUMERIC,
    "EXPGSC1_t_qd" NUMERIC,
    "IMPGSC1_t_qd" NUMERIC,
    "DPIC96_t_qd" NUMERIC,
    "IPB51110SQ_t_qd" NUMERIC,
    "IPB51220SQ_t_qd" NUMERIC,
    "USPRIV_t_qd" NUMERIC,
    "USEHS_t_qd" NUMERIC,
    "USINFO_t_qd" NUMERIC,
    "USPBS_t_qd" NUMERIC,
    "USLAH_t_qd" NUMERIC,
    "USSERV_t_qd" NUMERIC,
    "USMINE_t_qd" NUMERIC,
    "CES9091000001_t_qd" NUMERIC,
    "CES9092000001_t_qd" NUMERIC,
    "CES9093000001_t_qd" NUMERIC,
    "CIVPART_t_qd" NUMERIC,
    "UNRATESTx_t_qd" NUMERIC,
    "UNRATELTx_t_qd" NUMERIC,
    "LNS14000012_t_qd" NUMERIC,
    "LNS14000025_t_qd" NUMERIC,
    "LNS14000026_t_qd" NUMERIC,
    "LNS12032194_t_qd" NUMERIC,
    "HOABS_t_qd" NUMERIC,
    "HOANBS_t_qd" NUMERIC,
    "HWIx_t_qd" NUMERIC,
    "HOUST5F_t_qd" NUMERIC,
    "RSAFSx_t_qd" NUMERIC,
    "PCECTPI_t_qd" NUMERIC,
    "PCEPILFE_t_qd" NUMERIC,
    "GDPCTPI_t_qd" NUMERIC,
    "GPDICTPI_t_qd" NUMERIC,
    "IPDBS_t_qd" NUMERIC,
    "DGDSRG3Q086SBEA_t_qd" NUMERIC,
    "DDURRG3Q086SBEA_t_qd" NUMERIC,
    "DSERRG3Q086SBEA_t_qd" NUMERIC,
    "DNDGRG3Q086SBEA_t_qd" NUMERIC,
    "DHCERG3Q086SBEA_t_qd" NUMERIC,
    "DMOTRG3Q086SBEA_t_qd" NUMERIC,
    "DFDHRG3Q086SBEA_t_qd" NUMERIC,
    "DREQRG3Q086SBEA_t_qd" NUMERIC,
    "DODGRG3Q086SBEA_t_qd" NUMERIC,
    "DFXARG3Q086SBEA_t_qd" NUMERIC,
    "DCLORG3Q086SBEA_t_qd" NUMERIC,
    "DGOERG3Q086SBEA_t_qd" NUMERIC,
    "DONGRG3Q086SBEA_t_qd" NUMERIC,
    "DHUTRG3Q086SBEA_t_qd" NUMERIC,
    "DHLCRG3Q086SBEA_t_qd" NUMERIC,
    "DTRSRG3Q086SBEA_t_qd" NUMERIC,
    "DRCARG3Q086SBEA_t_qd" NUMERIC,
    "DFSARG3Q086SBEA_t_qd" NUMERIC,
    "DIFSRG3Q086SBEA_t_qd" NUMERIC,
    "DOTSRG3Q086SBEA_t_qd" NUMERIC,
    "CPILFESL_t_qd" NUMERIC,
    "PPIACO_t_qd" NUMERIC,
    "WPSFD4111_t_qd" NUMERIC,
    "PPIIDC_t_qd" NUMERIC,
    "WPU0561_t_qd" NUMERIC,
    "CES2000000008x_t_qd" NUMERIC,
    "CES3000000008x_t_qd" NUMERIC,
    "COMPRNFB_t_qd" NUMERIC,
    "RCPHBS_t_qd" NUMERIC,
    "OPHNFB_t_qd" NUMERIC,
    "ULCBS_t_qd" NUMERIC,
    "ULCNFB_t_qd" NUMERIC,
    "UNLPNBS_t_qd" NUMERIC,
    "BAA10YM_t_qd" NUMERIC,
    "TB6M3Mx_t_qd" NUMERIC,
    "GS1TB3Mx_t_qd" NUMERIC,
    "GS10TB3Mx_t_qd" NUMERIC,
    "CPF3MTB3Mx_t_qd" NUMERIC,
    "BOGMBASEREALx_t_qd" NUMERIC,
    "M1REAL_t_qd" NUMERIC,
    "BUSLOANSx_t_qd" NUMERIC,
    "CONSUMERx_t_qd" NUMERIC,
    "NONREVSLx_t_qd" NUMERIC,
    "REALLNx_t_qd" NUMERIC,
    "TOTALSLx_t_qd" NUMERIC,
    "TABSHNOx_t_qd" NUMERIC,
    "TLBSHNOx_t_qd" NUMERIC,
    "LIABPIx_t_qd" NUMERIC,
    "TNWBSHNOx_t_qd" NUMERIC,
    "NWPIx_t_qd" NUMERIC,
    "TARESAx_t_qd" NUMERIC,
    "HNOREMQ027Sx_t_qd" NUMERIC,
    "TFAABSHNOx_t_qd" NUMERIC,
    "B020RE1Q156NBEA_t_qd" NUMERIC,
    "B021RE1Q156NBEA_t_qd" NUMERIC,
    "HWIURATIOx_t_qd" NUMERIC,
    "CONSPIx_t_qd" NUMERIC,
    "CP3M_t_qd" NUMERIC,
    "COMPAPFF_t_qd" NUMERIC,
    "NIKKEI225_t_qd" NUMERIC,
    "TLBSNNCBx_t_qd" NUMERIC,
    "TLBSNNCBBDIx_t_qd" NUMERIC,
    "TTAABSNNCBx_t_qd" NUMERIC,
    "TNWMVBSNNCBx_t_qd" NUMERIC,
    "TNWMVBSNNCBBDIx_t_qd" NUMERIC,
    "TLBSNNBx_t_qd" NUMERIC,
    "TLBSNNBBDIx_t_qd" NUMERIC,
    "TABSNNBx_t_qd" NUMERIC,
    "TNWBSNNBx_t_qd" NUMERIC,
    "TNWBSNNBBDIx_t_qd" NUMERIC,
    "CNCFx_t_qd" NUMERIC,
    "covid_crash_qd" NUMERIC,
    "covid_recover_qd" NUMERIC,
    PRIMARY KEY (sasdate)
);

ALTER TABLE filled_qd ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon can read filled_qd" ON filled_qd;
CREATE POLICY "anon can read filled_qd"
    ON filled_qd
    FOR SELECT
    TO anon
    USING (true);

--------------------------------------------------------------
-- TABLE: dm_test
--------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dm_test (
    "version" NUMERIC,
    "model_1" NUMERIC,
    "model_2" NUMERIC,
    "test_statistic" NUMERIC,
    "p_value" NUMERIC,
    PRIMARY KEY (sasdate)
);

ALTER TABLE dm_test ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon can read dm_test" ON dm_test;
CREATE POLICY "anon can read dm_test"
    ON dm_test
    FOR SELECT
    TO anon
    USING (true);

-- ────────────────────────────────────────────────────────────
-- TABLE: model_forecasts
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS model_forecasts (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    run_date      DATE        NOT NULL,
    model_name    TEXT        NOT NULL,
    quarter_date       DATE        NOT NULL,
    month_date    DATE        NOT NULL,
    nowcast       NUMERIC     NOT NULL,
    ci_50_lb      NUMERIC     NOT NULL,
    ci_50_ub      NUMERIC     NOT NULL,
    ci_80_lb      NUMERIC     NOT NULL,
    ci_80_ub      NUMERIC     NOT NULL,

    -- Upsert key: one forecast per model per month
    -- When pipeline revises a month's estimate, this
    -- constraint ensures we overwrite rather than duplicate
    CONSTRAINT model_forecasts_unique UNIQUE (model_name, quarter_date, month_date)
);

CREATE INDEX IF NOT EXISTS idx_model_forecasts_month_date
    ON model_forecasts (month_date);

CREATE INDEX IF NOT EXISTS idx_model_forecasts_model_name
    ON model_forecasts (model_name);

ALTER TABLE model_forecasts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon can read model_forecasts" ON model_forecasts;
CREATE POLICY "anon can read model_forecasts"
    ON model_forecasts
    FOR SELECT
    TO anon
    USING (true);
